export default styles = {
  video: "video",
  bgVideo: "bgVideo",
  content: "content",
  section: "section",
  paragraph: "paragraph",
  title: "title",
  button: "button",
  gold: "gold",
  emerald: "emerald",
  wrapper: "wrapper",
  caption: "caption",
  container: "container",
  playButton: "playButton",
  soundButton: "soundButton",
  image: "image",
};
